language: node_js
sudo: required
services:
- docker
node_js: 8
script: |
  npm run build
  docker build -t ${DOCKER_USER}/about .
after_success: |
  echo $(DOCKER_PASS) | docker login -u $(DOCKER_USER) --password-stdin \
  && docker push ${DOCKER_USER}/about
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST https://dashboard-api.vibioh.fr/containers/about/ --data-binary @docker-compose.yml'
  on:
    all_branches: true
    condition: ${TRAVIS_BRANCH} == 'master'
- provider: script
  skip_cleanup: true
  script: >-
    cat docker-compose.yml | sed "s|traefik.frontend.rule.*|traefik.frontend.rule: 'Host: www-${TRAVIS_BRANCH}.vibioh.fr'|" | sed "s|${DOCKER_IMAGE_DEFAULT}|${DOCKER_IMAGE_NAME}|" | curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/about-${TRAVIS_BRANCH}/ --data-binary @-
  on:
    all_branches: true
    condition: ${TRAVIS_BRANCH} != 'master'
