jobs:
  include:
  - stage: Build

    sudo: required
    language: minimal
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=${TRAVIS_COMMIT}" -t "${DOCKER_USER}/about:${TRAVIS_COMMIT}" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker push "${DOCKER_USER}/about:${TRAVIS_COMMIT}"

  - stage: Publish

    sudo: required
    language: minimal
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker pull "${DOCKER_USER}/about:${TRAVIS_COMMIT}"
    - docker tag "${DOCKER_USER}/about:${TRAVIS_COMMIT}" "${DOCKER_USER}/about:latest"
    - docker push "${DOCKER_USER}/about:latest"

  - stage: Deploy

    language: minimal
    script:
    - curl -q -sSL "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy"
    - scripts/deploy about "@docker-compose.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
