---

jobs:
  include:
    - stage: Build

      language: javascript
      node_js: 13
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - sudo systemctl restart docker
      script:
        - npm run build
        - git --no-pager diff && git diff --quiet
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "release"
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - DOCKER_IMAGE="${DOCKER_USER}/about" IMAGE_VERSION="${TRAVIS_COMMIT:0:8}" ./scripts/release docker
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Publish

      language: minimal
      script:
        - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
        - scripts/docker_promote "${DOCKER_USER}/about" "${TRAVIS_COMMIT:0:8}"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push

notifications:
  email: false
