jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=${TRAVIS_COMMIT}" -t vibioh/about:${TRAVIS_COMMIT} .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker push "vibioh/about:${TRAVIS_COMMIT}"

  - stage: Publish

    sudo: required
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker pull "vibioh/about:${TRAVIS_COMMIT}"
    - docker tag "vibioh/about:${TRAVIS_COMMIT}" vibioh/about:latest
    - docker push vibioh/about:latest

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: |
        curl -q -sSL "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy"
        scripts/deploy about "@docker-compose.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
