version: '2'

services:
  site:
    image: vibioh/about
    command:
    - -csp
    - default-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' fonts.gstatic.com
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: vibioh.fr, www.vibioh.fr'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 16777216
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
