---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: about
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app
      version: "0.0.21"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 10m

  values:
    nameOverride: about

    image:
      repository: vibioh/about

    config:
      VIWS_LOGGER_JSON: "true"

    ingress:
      enabled: true
      hosts:
        - vibioh.fr
        - www.vibioh.fr
      redirect:
        regex: ^https?://www.vibioh.fr(.*)
        replacement: https://vibioh.fr${1}
