---
nameOverride: about

image:
  repository: vibioh/about

config:
  VIWS_LOGGER_JSON: "true"

ingress:
  enabled: true
  hosts:
    - vibioh.fr
    - www.vibioh.fr
  redirect:
    regex: ^https?://www.vibioh.fr(.*)
    replacement: https://vibioh.fr${1}
