---
apiVersion: v1
kind: Service
metadata:
  name: about
  labels:
    app.kubernetes.io/name: about
    app.kubernetes.io/instance: about
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: about
  ports:
    - name: http
      port: 80
      targetPort: http
