apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: about
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.74"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: about
    image:
      name: vibioh/about
      tag: "202108062046" # {"$imagepolicy": "default:flux-about-web:tag"}
    config:
      VIWS_LOGGER_JSON: "true"
      VIWS_PROMETHEUS_GZIP: "false"
      VIWS_GZIP: "false"
    ingress:
      enabled: true
      hosts:
        - vibioh.fr
        - www.vibioh.fr
      redirect:
        regex: ^https?://www.vibioh.fr(.*)
        replacement: https://vibioh.fr${1}
    canary:
      enabled: true
      url: https://vibioh.fr
