apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: about
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.66"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: about
    image:
      name: vibioh/about
      tag: "202104151322" # {"$imagepolicy": "default:flux-about-web:tag"}
    config:
      VIWS_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - vibioh.fr
      - www.vibioh.fr
      redirect:
        regex: ^https?://www.vibioh.fr(.*)
        replacement: https://vibioh.fr${1}
    canary:
      enabled: true
      url: https://vibioh.fr
