apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: about
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.92"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: about
    image:
      name: vibioh/about
      tag: "202312141638" # {"$imagepolicy": "default:flux-about-web:tag"}
    config:
      GOMAXPROCS: "1"
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/about-me
      OTEL_SERVICE_NAME: about-me
      VIWS_GZIP: "false"
      VIWS_LOGGER_JSON: "true"
      VIWS_TELEMETRY_URL: datadog.observability:4317
    ingress:
      enabled: true
      compress: true
      hosts:
        - vibioh.fr
        - www.vibioh.fr
      redirect:
        regex: ^https?://www.vibioh.fr(.*)
        replacement: https://vibioh.fr${1}
    pprof:
      enabled: true
