apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: about
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: about
    image:
      name: vibioh/about
      tag: "202403202103" # {"$imagepolicy": "default:flux-about-web:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "about-me"
      tags.datadoghq.com/version: "202403202103" # {"$imagepolicy": "default:flux-about-web:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/about-me
      VIWS_GZIP: "false"
      VIWS_LOGGER_JSON: "true"
      VIWS_TELEMETRY_URL: datadog.observability:4317
    pprof:
      enabled: true
    autoscaling:
      enabled: false
